name: CI – Python unit tests

on:
  push:
    branches: [main, dev]      # run on pushes to these branches
  pull_request:                    # and on every PR

jobs:
  test:
    runs-on: ubuntu-latest

    # Run the matrix if you want to verify several Python versions;
    # drop the matrix block if you only care about one.
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      # 1. Check out your code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up the requested Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"            # speeds-up subsequent runs

      # 3. Install project & dev dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you keep test-only deps separate, include them too:
          # pip install -r requirements-dev.txt

      # 4. Run the unit-test suite
      - name: Run unit tests
        run: |
          python -m unittest discover -s ./tests -p "test_*.py" -v
