name: CI - Python unit tests

on:
  push:
    branches: [main, aj-pytorch]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests with coverage
      - name: Run unit tests with coverage
        working-directory: ./backend
        run: |
          coverage run --omit="*/_remote_module_non_scriptable.py" -m unittest discover -s ./tests -p "test_*.py" -v
          coverage xml

      # 5. Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
